package application

import (
	"context"
	"errors"
	"sync"
	"time"

	"github.com/teddymail/bagualu/internal/domain"
)

// BaselineChecker verifies external network reachability BEFORE each test round.
// MUST use the OpenWrt default exit, never Bagualu's Mihomo instance (SDD 7.4.2).
type BaselineChecker interface {
	Check(ctx context.Context) BaselineResult
}

// BaselineResult reports whether the external network baseline is available.
type BaselineResult struct {
	Available bool
	ErrorCode string // domain.ErrCodeBaselineUnavailable or ErrCodeBaselineLost
	Target    string
	Probes    int
	Received  int
}

// LoadStatus classifies exit-network load before a throughput test (SDD 7.4.3).
type LoadStatus string

const (
	LoadClean     LoadStatus = "clean"
	LoadBusy      LoadStatus = "network_busy"
	LoadUnknown   LoadStatus = "network_load_unknown"
	LoadContended LoadStatus = "network_contended"
)

// LoadResult is returned by LoadGuard.Check.
type LoadResult struct {
	Status                                                               LoadStatus
	UploadBps, DownloadBps                                               float64
	WANDownloadBefore, WANDownloadAfter, WANUploadBefore, WANUploadAfter int64
	DownloadCapacityBPS, UploadCapacityBPS, Threshold                    float64
	SampleDurationMS                                                     int64
}

// LoadGuard checks exit-network load before throughput tests (SDD 7.4.3).
// Only consulted for TestThroughput jobs.
type LoadGuard interface {
	Check(ctx context.Context) LoadResult
}

// ContentionChecker optionally inspects the network after a throughput run.
// Implementations can use the task result to subtract the bytes generated by
// Bagualu and classify the sample as externally contended.
type ContentionChecker interface {
	CheckDuring(ctx context.Context, outcome domain.MeasurementOutcome) LoadResult
}

// TestJob describes a single measurement task for any of the three test kinds.
// All three kinds share the same single-threaded queue (SDD 7.4.1).
type TestJob struct {
	ID                string
	NodeID            string
	Kind              domain.TestKind
	OnStart           func()
	Retry             int
	SpeedSourceHealth func(context.Context) error
	ContentionCheck   func(context.Context, domain.MeasurementOutcome) LoadResult
	// Run executes the measurement and returns a MeasurementOutcome.
	// The Orchestrator wraps Run with baseline and load checks.
	Run func(ctx context.Context) (domain.MeasurementOutcome, error)
}

// Orchestrator wraps TestQueue to enforce:
//   - baseline check before EVERY test kind (SDD 7.4.2)
//   - load guard before throughput tests (SDD 7.4.3)
//   - unified MeasurementOutcome (SDD 7.3)
//   - strict success validation: request success + node evidence + traffic growth (SDD 4.4 step 8)
//
// All three measurement kinds (connectivity, ping, throughput) share the same
// TestQueue; the single-threaded constraint is enforced by TestQueue itself.
type Orchestrator struct {
	queue            *TestQueue
	baseline         BaselineChecker
	guard            LoadGuard
	onResult         func(domain.MeasurementOutcome)
	mu               sync.Mutex
	jobs             map[string]TestJob
	loadResults      map[string]LoadResult
	baselineObserved bool
	baselineReady    bool
}

// NewOrchestrator creates an Orchestrator.
// onResult is called with the final MeasurementOutcome after each job completes.
// onResult may be nil if the caller does not need results.
func NewOrchestrator(
	queue *TestQueue,
	baseline BaselineChecker,
	guard LoadGuard,
	onResult func(domain.MeasurementOutcome),
) *Orchestrator {
	if queue == nil {
		queue = NewTestQueue(1)
	}
	return &Orchestrator{queue: queue, baseline: baseline, guard: guard, onResult: onResult, jobs: make(map[string]TestJob), loadResults: make(map[string]LoadResult)}
}

// Submit wraps job.Run with baseline / load checks and enqueues it on the shared queue.
// Returns ErrQueueFull if the queue is at capacity.
func (o *Orchestrator) Submit(job TestJob) error {
	req := TestRequest{
		ID:      job.ID,
		NodeID:  job.NodeID,
		Kind:    string(job.Kind),
		Run:     o.wrapJob(job),
		OnStart: job.OnStart,
	}
	o.mu.Lock()
	o.jobs[job.ID] = job
	o.mu.Unlock()
	if err := o.queue.Enqueue(req); err != nil {
		o.mu.Lock()
		delete(o.jobs, job.ID)
		o.mu.Unlock()
		return err
	}
	return nil
}

// Cancel cancels a pending or running task. Pending tasks receive a terminal
// cancelled outcome immediately; running tasks observe context cancellation.
func (o *Orchestrator) Cancel(id string) (bool, error) {
	o.mu.Lock()
	job, ok := o.jobs[id]
	o.mu.Unlock()
	if !ok {
		return false, nil
	}
	found, running := o.queue.Cancel(id)
	if !found {
		return false, nil
	}
	if !running {
		o.deliver(domain.MeasurementOutcome{JobID: job.ID, NodeID: job.NodeID, Kind: job.Kind,
			Status: "cancelled", ErrorCode: "cancelled", FailureStage: "queue", Infrastructure: true})
	}
	return true, nil
}

func (o *Orchestrator) wrapJob(job TestJob) func(ctx context.Context) error {
	return func(ctx context.Context) error {
		var outcome domain.MeasurementOutcome
		var err error
		for attempt := 0; ; attempt++ {
			if blocked := o.beforeAttempt(ctx, job); blocked != nil {
				o.deliver(*blocked)
				return nil
			}
			if job.SpeedSourceHealth != nil && job.Kind == domain.TestThroughput {
				if sourceErr := job.SpeedSourceHealth(ctx); sourceErr != nil {
					outcome := domain.MeasurementOutcome{JobID: job.ID, NodeID: job.NodeID, Kind: job.Kind,
						Status: "scheduled", ErrorCode: domain.ErrCodeSpeedSourceUnavailable,
						FailureStage: "speed_source", Infrastructure: true}
					applyLoadResult(&outcome, o.loadResult(job.ID))
					o.deliver(outcome)
					return nil
				}
			}
			outcome, err = job.Run(ctx)
			applyLoadResult(&outcome, o.loadResult(job.ID))
			if err == nil {
				var after BaselineResult
				if o.baseline == nil {
					after.ErrorCode = domain.ErrCodeBaselineLost
				} else {
					after = o.baseline.Check(ctx)
				}
				o.mu.Lock()
				o.baselineObserved = true
				o.baselineReady = after.Available
				o.mu.Unlock()
				if !after.Available {
					outcome.Success = false
					outcome.Status = "paused"
					outcome.ErrorCode = domain.ErrCodeBaselineLost
					outcome.FailureStage = "baseline_after"
					outcome.Infrastructure = true
				}
				if outcome.BaselineTarget == "" {
					outcome.BaselineTarget = after.Target
				}
			}
			if err == nil && job.Kind == domain.TestThroughput {
				if checker := o.contentionChecker(job); checker != nil {
					load := checker(ctx, outcome)
					if load.Status != LoadClean {
						outcome.Success = false
						outcome.Status = "scheduled"
						outcome.ErrorCode = string(load.Status)
						outcome.FailureStage = "load"
						outcome.Infrastructure = true
					}
					outcome.LoadStatus = string(load.Status)
					outcome.BackgroundUploadBPS = load.UploadBps
					outcome.BackgroundDownloadBPS = load.DownloadBps
					applyLoadResult(&outcome, load)
				}
			}
			if err == nil || attempt >= job.Retry || errors.Is(err, context.Canceled) {
				break
			}
			select {
			case <-ctx.Done():
				err = ctx.Err()
			case <-time.After(time.Duration(attempt+1) * 100 * time.Millisecond):
			}
			if ctx.Err() != nil {
				break
			}
		}
		outcome.JobID = job.ID
		outcome.NodeID = job.NodeID
		outcome.Kind = job.Kind

		if errors.Is(err, context.Canceled) {
			outcome.Status = "cancelled"
			outcome.ErrorCode = "cancelled"
			outcome.Success = false
			outcome.Infrastructure = true
			err = nil
		} else if err != nil {
			outcome.Success = false
			if outcome.ErrorCode == "" {
				var coded interface{ ErrorCode() string }
				if errors.As(err, &coded) && coded.ErrorCode() != "" {
					outcome.ErrorCode = coded.ErrorCode()
				} else {
					outcome.ErrorCode = domain.ErrCodeMeasurementFailed
				}
			}
			if outcome.Status == "" {
				outcome.Status = "failed"
			}
		}
		if outcome.Success && !validateOutcome(outcome) {
			outcome.Success = false
			if outcome.ErrorCode == "" {
				outcome.ErrorCode = domain.ErrCodeCoreRouteUnverified
			}
		}

		o.deliver(outcome)
		return err
	}
}

func (o *Orchestrator) beforeAttempt(ctx context.Context, job TestJob) *domain.MeasurementOutcome {
	var baseline BaselineResult
	if o.baseline == nil {
		baseline.ErrorCode = domain.ErrCodeBaselineUnavailable
	} else {
		baseline = o.baseline.Check(ctx)
	}
	o.mu.Lock()
	wasObserved := o.baselineObserved
	wasReady := o.baselineReady
	o.baselineObserved = true
	o.baselineReady = baseline.Available
	o.mu.Unlock()
	if !baseline.Available {
		code := baseline.ErrorCode
		if code == "" {
			code = domain.ErrCodeBaselineUnavailable
		}
		return &domain.MeasurementOutcome{JobID: job.ID, NodeID: job.NodeID, Kind: job.Kind,
			Status: "paused", ErrorCode: code, FailureStage: "baseline", Infrastructure: true,
			BaselineTarget: baseline.Target}
	}
	if wasObserved && !wasReady {
		timer := time.NewTimer(time.Second)
		select {
		case <-ctx.Done():
			timer.Stop()
			return &domain.MeasurementOutcome{JobID: job.ID, NodeID: job.NodeID, Kind: job.Kind,
				Status: "cancelled", ErrorCode: "cancelled", FailureStage: "baseline", Infrastructure: true}
		case <-timer.C:
		}
		var recovery BaselineResult
		if o.baseline == nil {
			recovery.ErrorCode = domain.ErrCodeBaselineUnavailable
		} else {
			recovery = o.baseline.Check(ctx)
		}
		if !recovery.Available {
			code := recovery.ErrorCode
			if code == "" {
				code = domain.ErrCodeBaselineUnavailable
			}
			o.mu.Lock()
			o.baselineReady = false
			o.mu.Unlock()
			return &domain.MeasurementOutcome{JobID: job.ID, NodeID: job.NodeID, Kind: job.Kind,
				Status: "paused", ErrorCode: code, FailureStage: "baseline_recovery", Infrastructure: true,
				BaselineTarget: recovery.Target}
		}
		o.mu.Lock()
		o.baselineReady = true
		o.mu.Unlock()
	}
	if job.Kind == domain.TestThroughput {
		load := LoadResult{Status: LoadUnknown}
		if o.guard != nil {
			load = o.guard.Check(ctx)
		}
		o.mu.Lock()
		o.loadResults[job.ID] = load
		o.mu.Unlock()
		if load.Status != LoadClean {
			code := string(load.Status)
			if code == "" {
				code = domain.ErrCodeNetworkLoadUnknown
			}
			outcome := &domain.MeasurementOutcome{JobID: job.ID, NodeID: job.NodeID, Kind: job.Kind,
				Status: "scheduled", ErrorCode: code, FailureStage: "load", Infrastructure: true,
				LoadStatus: string(load.Status), BackgroundUploadBPS: load.UploadBps,
				BackgroundDownloadBPS: load.DownloadBps}
			applyLoadResult(outcome, load)
			return outcome
		}
	}
	return nil
}

func (o *Orchestrator) contentionChecker(job TestJob) func(context.Context, domain.MeasurementOutcome) LoadResult {
	if job.ContentionCheck != nil {
		return job.ContentionCheck
	}
	if checker, ok := o.guard.(ContentionChecker); ok {
		return checker.CheckDuring
	}
	return nil
}

func (o *Orchestrator) deliver(outcome domain.MeasurementOutcome) {
	o.mu.Lock()
	delete(o.jobs, outcome.JobID)
	delete(o.loadResults, outcome.JobID)
	o.mu.Unlock()
	if o.onResult != nil {
		o.onResult(outcome)
	}
}

func (o *Orchestrator) loadResult(jobID string) LoadResult {
	o.mu.Lock()
	defer o.mu.Unlock()
	return o.loadResults[jobID]
}

func applyLoadResult(outcome *domain.MeasurementOutcome, load LoadResult) {
	if outcome == nil || load.Status == "" {
		return
	}
	outcome.LoadStatus = string(load.Status)
	outcome.BackgroundUploadBPS = load.UploadBps
	outcome.BackgroundDownloadBPS = load.DownloadBps
	outcome.WANDownloadBefore = load.WANDownloadBefore
	outcome.WANDownloadAfter = load.WANDownloadAfter
	outcome.WANUploadBefore = load.WANUploadBefore
	outcome.WANUploadAfter = load.WANUploadAfter
	outcome.WANDownloadCapacityBPS = load.DownloadCapacityBPS
	outcome.WANUploadCapacityBPS = load.UploadCapacityBPS
	outcome.LoadThreshold = load.Threshold
	outcome.LoadSampleDurationMS = load.SampleDurationMS
}

// validateOutcome enforces the SDD 4.4 step 8 contract:
// connectivity and throughput MUST have confirmed node evidence.
// throughput MUST show traffic growth.
// ping results do not require core evidence (ICMP is not via Mihomo).
func validateOutcome(outcome domain.MeasurementOutcome) bool {
	switch outcome.Kind {
	case domain.TestConnectivity, domain.TestThroughput:
		if outcome.Evidence.NodeName == "" {
			return false
		}
		if outcome.Evidence.TrafficAfter <= outcome.Evidence.TrafficBefore {
			return false
		}
	}
	return true
}
